src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Iso_Code__c</fullName>
        <externalId>true</externalId>
        <label>Iso Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Countries</relationshipLabel>
        <relationshipName>Partner_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Countries</relationshipLabel>
        <relationshipName>Partner_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Country</label>
    <nameField>
        <label>Partner Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Strength__c.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Strengths</relationshipLabel>
        <relationshipName>Partner_Strengths</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Social_Performance_Strength__c</fullName>
        <label>Social Performance Strength</label>
        <referenceTo>Social_Performance_Strength__c</referenceTo>
        <relationshipLabel>Partner Strengths</relationshipLabel>
        <relationshipName>Partner_Strengths</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Strength</label>
    <nameField>
        <label>Partner Strength Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Strengths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Social_Performance_Strength__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Social Performance Strength</label>
    <nameField>
        <label>Social Performance Strength Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Performance Strengths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
	
	public static void createJunctionObjects( List<Account> accounts ) {
		List<Partner_Strength__c> partnerStrengths = new List<Partner_Strength__c>();
		List<Partner_Country__c> partnerCountries = new List<Partner_Country__c>();
		
		Map<String, List<Id>> strengthIdToPartners = new Map<String, List<Id>>();
		Map<String, List<Id>> countryIsoToPartners = new Map<String, List<Id>>();
		
		for(Account a : accounts){
			
			if(a.PartnerStrength_Ids__c != null){
				for(String s : a.PartnerStrength_Ids__c.split(';')){
					if( strengthIdToPartners.containsKey( s )) strengthIdToPartners.get(s).add(a.Id);
					else strengthIdToPartners.put( s, new List<Id>{a.Id});
				}
			}
			
			if( a.Country_Codes__c != null ){
				for( String s : a.Country_Codes__c.split(';')) {
					if( countryIsoToPartners.containsKey( s ) ) countryIsoToPartners.get(s).add(a.Id);
					else countryIsoToPartners.put( s, new List<Id>{a.Id});
				}
			}
			
		}
		
		
		System.debug('strengthIdToPartners: ' + strengthIdToPartners);
		System.debug('countryIsoToPartners: ' + countryIsoToPartners);
		
		for( Social_Performance_Strength__c s : [SELECT Id, Id__c, Name FROM Social_Performance_Strength__c WHERE Id__c IN :strengthIdToPartners.keyset()]){
			for( Id aId : strengthIdToPartners.get(s.Id__c) ){
				partnerStrengths.add( new Partner_Strength__c(	Name= s.Name,
																Social_Performance_Strength__c = s.Id,
																Partner__c = aId ) );				
			}
		}
		
		for( Country__c c : [SELECT Id, Name, Iso_Code__c FROM Country__c WHERE Iso_Code__c IN :countryIsoToPartners.keyset()]){
			for(Id aId : countryIsoToPartners.get(c.Iso_Code__c)){
				partnerCountries.add( new Partner_Country__c( 	Name = c.Name,
																Country__c = c.Id,
																Partner__c = aId ) );
			}
		}
		
		System.debug('partnerStrengths: ' + partnerStrengths);
		System.debug('partnerCountries: ' + partnerCountries);

		try{
			insert partnerStrengths;
			insert partnerCountries;
		} catch(DmlException e){
			System.debug('AccountTriggerHandler.createJunctionObjects: ' + e);
		}
		
	}
}